version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: honeybee-energy
    versions:
    - ">= 0"
  - dependency-name: importlib-metadata
    versions:
    - 3.7.2
